### PR TITLE
Tnf x supreme 

### PR DESCRIPTION
**Pull request by HolgerDA**
Ved du om kan kører to scripts på samme tid? går nemlig både efter den tynde og tykke jakke på torsdag.
Tænker chancen ville være større istedet for at køre det på den samme?

### CODE REVIEW

**Comment by Hezion** [comment]
Worst pull request i have ever seen. Plus you need to write in English.

**Comment by HolgerDA** [comment]
Hahah sorry thought this was some kind of place to ask questions, and didn't knew that there were anyone else than him following this, and i know he is Danish too

**Comment by colincowie** [comment]
You can run my version of the bot twice at the same time with out errors

**Comment by kaaetech** [comment]
Well, with my version you can buy two items at once 0.1 seconds slower or something

**Comment by colincowie** [comment]
Both mine and kaaetech' versions work well, phantomJS uses a lot less memory then chrome so you could run multiple instances with out heavily losses but with kaaetech you can purchase two on the same instance. :)

**Pull request closed without merging**
